	--先删除
	DELETE FROM moky.DS.dbo.GameActor WHERE ActorID IN(161354)
	DELETE FROM moky.DS.dbo.GameActor2 WHERE ActorID IN(161354)
	DELETE FROM moky.DS.dbo.GameGoods WHERE ActorID IN(161354)
	go
	--再复制
	INSERT INTO moky.DS.dbo.[GameActor]([ActorID]
      ,[ActorName]
      ,[UserID]
      ,[CreateTime]
      ,[LoginID]
      ,[ZoneID]
      ,[Deleted]
      ,[VipLevel]
      ,[Emblem]
      ,[Vocation]
      ,[Power]
      ,[Energy]
      ,[VipScore]
      ,[Exp]
      ,[EnergyTime]
      ,[UpgradeTime]
      ,[Recharge]
      ,[Diamond]
      ,[Money]
      ,[Moral]
      ,[Train]
      ,[Prestige]
      ,[PacketSize]
      ,[PacketAvailableSize]
      ,[MapID]
      ,[PosX]
      ,[PosY]
      ,[PosZ]
      ,[WeaponData]
      ,[LogicData]
      ,[EctypeHead]
      ,[EctypeData]
      ,[SkillData]
      ,[StoreData]
      ,[FacadeData]
      ,[SocietyHead]
      ,[SocietyData]
      ,[Country]
      ,[FashionData]
      ,[MdyTime]
      ,[LastLoginTime]
      ,[LastLogoutTime]
      ,[LastOnlineSecs]
      ,[Cost]
      ,[WeaponPower]
      ,[BableFloor]
      ,[GemStorageSize]
      ,[GemData]
      ,[DenyLogin]
      ,[DenyLogin_OpTime]
      ,[OperName]
      ,[UserSrc]
      ,[ActorLvl]
      ,[Charm]
      ,[通天塔层数]
      ,[通天塔时间]
      ,[ActorLvlTime]
      ,[WildBattleKillNum]
      ,[WildBattleContKill]
      ,[WildBattleKillNumPD]
      ,[WildBattleContKillPD]
      ,[WildBattleCurTime]) SELECT * FROM  [DS].dbo.[GameActor] 
	  WHERE ActorID IN(161354)
	
	INSERT INTO moky.DS.dbo.[GameActor2]([ActorID]
      ,[EquipGemData]
      ,[MountData]
      ,[WingData]
      ,[PKValue]
      ,[VocationSkill]
      ,[RuneSkill]
      ,[Practice]
      ,[SynthesisValue]
      ,[TaskData]
      ,[EctypeExtrData]
      ,[EctypeChapterData]
      ,[GodWeaponData]
      ,[TalentData]
      ,[Talent]
      ,[Exploit]
      ,[BindDiamond]
      ,[Coupons]
      ,[LifeSkillData]
      ,[LastOffTime]
      ,[SaveFlag]
      ,[CurrBindRune]
      ,[Achieve]
      ,[Military]
      ,[AdForbidTime]
      ,[MaxHp]
      ,[WuAttack]
      ,[WuDefense]
      ,[FaAttack]
      ,[FaDefense]
      ,[Crit]
      ,[CritDefense]
      ,[Through]
      ,[Parry]
      ,[Hit]
      ,[Dodge]
      ,[DamageAdd]
      ,[DamageReduction]
      ,[EquipModeID]
      ,[WeaponID]
      ,[WingID]
      ,[CountryFund]
      ,[ExchangeTicket]
      ,[BuffData]
      ,[CusPictureData]
      ,[NewWingData]
      ,[Aura]
      ,[PropertyDrug]
      ,[MountPower]
      ,[WingPower]
      ,[NewWingPower]
      ,[PropActive]
      ,[LogicData2]
      ,[GoldCoin]
      ,[Genre]
      ,[CurHP]) SELECT * FROM [DS].dbo.[GameActor2] 
	  WHERE ActorID IN(161354)
	
	--Identity Column是不能直接复制的，由数据库自动生成
	INSERT INTO moky.DS.dbo.[GameGoods] (UserID,ActorID,IDCard,GoodsID,GoodsQty,Flags,SkepID,Place,ValidTime,Quality,StarNum,SmeltExp,EnchLevel,SoulLevel,SoulExp,Custom,SkillLevel,GoodsType,GemID,EffectID,SmeltLevel,BaseEffectID,AddEffectID,SpecialSkill,GoodsUID,RowStatus,IsOnGround,MdyTime,ModuleID,MasterID,CrtTime) SELECT UserID,ActorID,IDCard,GoodsID,GoodsQty,Flags,SkepID,Place,ValidTime,Quality,StarNum,SmeltExp,EnchLevel,SoulLevel,SoulExp,Custom,SkillLevel,GoodsType,GemID,EffectID,SmeltLevel,BaseEffectID,AddEffectID,SpecialSkill,GoodsUID,RowStatus,IsOnGround,MdyTime,ModuleID,MasterID,CrtTime FROM [DS].dbo.[GameGoods] 
	WHERE ActorID IN(161354)